<?php

namespace ContainerT1OiWtX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XVv0CVvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XVv0CVv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XVv0CVv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::editUser' => ['privates', '.service_locator.Kntl2lG', 'get_ServiceLocator_Kntl2lGService', true],
            'App\\Controller\\AdminController::usersList' => ['privates', '.service_locator.h0QcpYw', 'get_ServiceLocator_H0QcpYwService', true],
            'App\\Controller\\HomeController::edit' => ['privates', '.service_locator.tYWY7uE', 'get_ServiceLocator_TYWY7uEService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator..RZs9q2', 'get_ServiceLocator__RZs9q2Service', true],
            'App\\Controller\\HomeController::new' => ['privates', '.service_locator.6hWhwyj', 'get_ServiceLocator_6hWhwyjService', true],
            'App\\Controller\\HomeController::show' => ['privates', '.service_locator.tYWY7uE', 'get_ServiceLocator_TYWY7uEService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.iTWUpOY', 'get_ServiceLocator_ITWUpOYService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AdminController:editUser' => ['privates', '.service_locator.Kntl2lG', 'get_ServiceLocator_Kntl2lGService', true],
            'App\\Controller\\AdminController:usersList' => ['privates', '.service_locator.h0QcpYw', 'get_ServiceLocator_H0QcpYwService', true],
            'App\\Controller\\HomeController:edit' => ['privates', '.service_locator.tYWY7uE', 'get_ServiceLocator_TYWY7uEService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator..RZs9q2', 'get_ServiceLocator__RZs9q2Service', true],
            'App\\Controller\\HomeController:new' => ['privates', '.service_locator.6hWhwyj', 'get_ServiceLocator_6hWhwyjService', true],
            'App\\Controller\\HomeController:show' => ['privates', '.service_locator.tYWY7uE', 'get_ServiceLocator_TYWY7uEService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.iTWUpOY', 'get_ServiceLocator_ITWUpOYService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AdminController::editUser' => '?',
            'App\\Controller\\AdminController::usersList' => '?',
            'App\\Controller\\HomeController::edit' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\HomeController::new' => '?',
            'App\\Controller\\HomeController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminController:editUser' => '?',
            'App\\Controller\\AdminController:usersList' => '?',
            'App\\Controller\\HomeController:edit' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\HomeController:new' => '?',
            'App\\Controller\\HomeController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
