<?php

namespace ContainerT1OiWtX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H0QcpYwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.h0QcpYw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h0QcpYw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'users' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'users' => 'App\\Repository\\UsersRepository',
        ]);
    }
}
