<?php

namespace ContainerT1OiWtX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVerfahrenService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.tYWY7uE.App\Entity\Verfahren' shared service.
     *
     * @return \App\Entity\Verfahren
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.tYWY7uE": it references class "App\\Entity\\Verfahren" but no such service exists.');
    }
}
