<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.88ab7134.js',
                '/build/22.5205218e.js',
                '/build/app.5c583b4a.js',
            ],
            'css' => [
                '/build/app.6f278f00.css',
            ],
        ],
    ],
],

]];
